### ISSUE TITLE
item shop

### ISSUE THREAD

**Issue by NuZiuki240Hz** [chloefrfr/ChronosPublic#5]
![image](https://github.com/user-attachments/assets/b20cbd69-e6dc-4a96-8606-5fbd64742104)

hello, why is the store on season 7 not working and neither the battle pass nor the matchmaker?

**Comment by frearkdev** [comment]
Hi! I'm not the creator of this backend but i'll help.

Battlepass: Season 7 battlepass is not added.
Shop: Because it has to be rotated on a time, you can rotate it yourself by using /rotate command
Matchmaker: I have no idea to be honest.

Hope this helps! :)

**Comment by PhysicalDrive** [comment]
Hi! I'm not the creator of this backend but i'll help.

Battlepass: Season 7 battlepass is not added.
Shop: Because it has to be rotated on a time, you can rotate it yourself by using /rotate command
Matchmaker: I have no idea to be honest.

Hope this helps! :)
